/**
 * dailyBriefService.ts — Daily concept-of-the-day brief
 * Cached per day in localStorage. No API key required.
 */

export interface DailyBrief {
  id: string;
  date: string;
  concept: string;
  subject: string;
  summary: string;         // 2-3 sentences
  quickFact: string;       // memorable 1-liner
  todayQuestion: {
    text: string;
    options: string[];
    answer: number;        // index into options
    explanation: string;
  };
  tip: string;
  examCountdown?: number;  // days to exam
  streakNote?: string;
}

const BRIEF_STORAGE = 'eg_daily_briefs';

// Concept library — rotates by day-of-month
const CONCEPT_LIBRARY = [
  {
    concept: "Faraday's Law of Electromagnetic Induction",
    subject: 'Electromagnetics',
    summary: "A changing magnetic flux through a loop induces an EMF. The induced EMF is directly proportional to the rate of change of flux. This is the foundation of electric generators and transformers.",
    quickFact: '⚡ EMF = -dΦ/dt — the negative sign is Lenz\'s Law in action!',
    todayQuestion: {
      text: 'A coil of 100 turns has flux changing at 0.01 Wb/s. What is the induced EMF?',
      options: ['0.1 V', '1 V', '10 V', '100 V'],
      answer: 1,
      explanation: 'EMF = N × dΦ/dt = 100 × 0.01 = 1V. Always multiply by number of turns!',
    },
    tip: '🎯 Always check the number of turns — GATE loves multi-turn coil traps!',
  },
  {
    concept: 'Time Complexity of Sorting Algorithms',
    subject: 'Computer Science',
    summary: 'Different sorting algorithms have different time complexities. Merge sort and heap sort guarantee O(n log n) in the worst case, while QuickSort is O(n²) worst case.',
    quickFact: '🔑 QuickSort: O(n²) worst case but O(n log n) average — pivot selection matters!',
    todayQuestion: {
      text: 'Which sorting algorithm is stable AND has O(n log n) worst-case complexity?',
      options: ['QuickSort', 'HeapSort', 'MergeSort', 'BubbleSort'],
      answer: 2,
      explanation: 'Merge Sort is stable (maintains relative order of equal elements) and always O(n log n)',
    },
    tip: '🎯 For GATE, know which algorithms are stable — it\'s asked almost every year!',
  },
  {
    concept: "Maxwell's Equations",
    subject: 'Electromagnetics',
    summary: "Maxwell's four equations are the foundation of classical electromagnetism. They describe how electric and magnetic fields are generated by charges, currents, and each other.",
    quickFact: "📡 Maxwell predicted electromagnetic waves before they were experimentally discovered!",
    todayQuestion: {
      text: "Which Maxwell equation is equivalent to Faraday's Law?",
      options: ['∇·E = ρ/ε₀', '∇·B = 0', '∇×E = -∂B/∂t', '∇×B = μ₀J + μ₀ε₀∂E/∂t'],
      answer: 2,
      explanation: '∇×E = -∂B/∂t is the differential form of Faraday\'s Law of induction',
    },
    tip: '🎯 Memorise all 4 Maxwell equations in both integral and differential form!',
  },
  {
    concept: 'Dijkstra\'s Shortest Path Algorithm',
    subject: 'Algorithms',
    summary: "Dijkstra's algorithm finds the shortest path from a source vertex to all other vertices in a weighted graph. It uses a greedy approach with a priority queue.",
    quickFact: '⚡ Dijkstra fails on negative edge weights — use Bellman-Ford instead!',
    todayQuestion: {
      text: "What is the time complexity of Dijkstra's algorithm with a binary heap?",
      options: ['O(V²)', 'O((V+E) log V)', 'O(V log V)', 'O(E²)'],
      answer: 1,
      explanation: 'With a binary min-heap: O((V+E) log V) since each edge relaxation is O(log V)',
    },
    tip: '🎯 GATE often asks which shortest path algorithm to choose — know the trade-offs!',
  },
  {
    concept: 'Thevenin\'s Theorem',
    subject: 'Circuit Theory',
    summary: "Any linear two-terminal circuit can be replaced by an equivalent circuit of a voltage source (Vth) in series with a resistance (Rth). This simplifies complex circuit analysis tremendously.",
    quickFact: '🔌 Vth = open-circuit voltage; Rth = resistance seen from terminals with sources zeroed!',
    todayQuestion: {
      text: "To find Rth in Thevenin's equivalent, independent voltage sources are:",
      options: ['Left as-is', 'Replaced with open circuit', 'Replaced with short circuit', 'Removed from circuit'],
      answer: 2,
      explanation: 'Independent voltage sources are short-circuited (V=0); independent current sources are open-circuited (I=0)',
    },
    tip: '🎯 For circuits with dependent sources, use V-test or I-test method for Rth!',
  },
  {
    concept: 'Pumping Lemma for Regular Languages',
    subject: 'Theory of Computation',
    summary: "The Pumping Lemma states that any string in a regular language that is longer than the pumping length p can be 'pumped' (its middle portion repeated any number of times) and still remain in the language.",
    quickFact: "🔑 Pumping Lemma proves languages are NOT regular — it's a tool for contradiction!",
    todayQuestion: {
      text: "Which language can be proven non-regular using the Pumping Lemma?",
      options: ['(ab)*', 'a*b*', 'aⁿbⁿ | n≥0', '(a|b)*ab'],
      answer: 2,
      explanation: 'aⁿbⁿ requires counting (n must match), which finite automata cannot do',
    },
    tip: '🎯 Always pick a specific string and show pumping fails — that\'s the proof technique!',
  },
  {
    concept: 'Bode Plot Analysis',
    subject: 'Control Systems',
    summary: "Bode plots show frequency response of a system — gain (dB) and phase (degrees) vs frequency (log scale). They are essential for analyzing stability and designing controllers.",
    quickFact: '📊 At gain crossover frequency, phase margin = 180° + phase angle',
    todayQuestion: {
      text: 'What is the slope (dB/decade) of a Bode magnitude plot for a simple pole?',
      options: ['+20 dB/dec', '-20 dB/dec', '+40 dB/dec', '-40 dB/dec'],
      answer: 1,
      explanation: 'A simple pole contributes -20 dB/decade slope above the corner frequency',
    },
    tip: '🎯 For GATE, remember: each pole → -20 dB/dec; each zero → +20 dB/dec!',
  },
  {
    concept: 'Virtual Memory and Paging',
    subject: 'Operating Systems',
    summary: "Virtual memory allows processes to use more memory than physically available by using disk as extension. Paging divides memory into fixed-size pages mapped to physical frames.",
    quickFact: "🖥️ Page table entry: Valid bit + Frame number + Protection bits + Reference bit + Dirty bit",
    todayQuestion: {
      text: 'Which page replacement algorithm guarantees optimal (minimum) page faults?',
      options: ['LRU', 'FIFO', 'Clock (Second Chance)', 'Optimal (OPT)'],
      answer: 3,
      explanation: 'OPT replaces the page that will not be used for the longest time in future. Not implementable in practice (requires future knowledge).',
    },
    tip: '🎯 Belady\'s anomaly only occurs in FIFO — more frames can cause MORE page faults!',
  },
];

export function getTodaysBrief(exam: string = 'GATE'): DailyBrief {
  const today = new Date().toDateString();
  const cacheKey = `${BRIEF_STORAGE}_${today}`;
  const cached = localStorage.getItem(cacheKey);
  if (cached) {
    try { return JSON.parse(cached) as DailyBrief; } catch { /* fall through */ }
  }

  const dayOfMonth = new Date().getDate();
  const concept = CONCEPT_LIBRARY[dayOfMonth % CONCEPT_LIBRARY.length];

  // Load streak from gamification profile
  let streakNote: string | undefined;
  try {
    const raw = localStorage.getItem('eg_gamification_profile');
    if (raw) {
      const p = JSON.parse(raw) as { streak: number };
      if (p.streak > 0) streakNote = `🔥 Day ${p.streak} streak — keep going!`;
    }
  } catch { /* ignore */ }

  const brief: DailyBrief = {
    id: today,
    date: today,
    ...concept,
    examCountdown: 60, // placeholder — real exam countdown from examDateService
    streakNote,
  };

  localStorage.setItem(cacheKey, JSON.stringify(brief));
  return brief;
}

export function markBriefAnswered(briefId: string, correct: boolean): void {
  const key = `eg_brief_answered_${briefId}`;
  localStorage.setItem(key, JSON.stringify({ correct, at: new Date().toISOString() }));
}

export function getBriefAnswerRecord(briefId: string): { correct: boolean; at: string } | null {
  try {
    const raw = localStorage.getItem(`eg_brief_answered_${briefId}`);
    if (raw) return JSON.parse(raw) as { correct: boolean; at: string };
  } catch { /* ignore */ }
  return null;
}

export function isBriefAnsweredToday(): boolean {
  const today = new Date().toDateString();
  return !!localStorage.getItem(`eg_brief_answered_${today}`);
}

export function getBriefHistory(days = 7): Array<{ brief: DailyBrief; answered: boolean; correct?: boolean }> {
  const history = [];
  for (let i = 0; i < days; i++) {
    const d = new Date(Date.now() - i * 86400000);
    const dateStr = d.toDateString();
    const cacheKey = `${BRIEF_STORAGE}_${dateStr}`;
    const raw = localStorage.getItem(cacheKey);
    if (raw) {
      try {
        const brief = JSON.parse(raw) as DailyBrief;
        const record = getBriefAnswerRecord(brief.id);
        history.push({ brief, answered: !!record, correct: record?.correct });
      } catch { /* skip */ }
    }
  }
  return history;
}
